# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d941e798b48a65309e705bb9f5479fc94be07fa57d20373b7195f35ebcf3372a7ad77ff612f1ff43ac8863a47ef5efecb8ae2501c637c901231482e4b3368453

test:
  secret_key_base: bfe9cad08abb682dbb72ca77d478eaaea0c358634a24bcc21e97655f63080c6c14286170a808e0d47922d8078e34cc12ceac9d04162476179825452b5e56c6fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
